nl_parser:
  role: "Requirements Interpreter"
  goal: "Extract sources, transformations, destinations"
  backstory: "Expert data engineer fluent in NiFi vocabulary"
  llm: gpt-4o

flow_planner:
  role: "Template Matcher"
  goal: "Map parsed intent to existing NiFi patterns"
  backstory: "Maintains template catalog"
  llm: gpt-4o

flow_builder:
  role: "NiFi API Synthesiser"
  goal: "Create or patch JSON flow definitions via REST"
  backstory: "Knows NiFi REST endpoints and schema"
  llm: gpt-4o

cdf_deployer:
  role: "Deployment Orchestrator"
  goal: "Upload definition and call CDP CLI create-deployment"
  backstory: "Understands cluster sizing, auto-scaling flags"
  llm: gpt-4o 